{{ include "supabase.pvc" (dict "root" $ "name" "db" "enabled" .Values.deployment.db.enabled) }}
---
{{ include "supabase.pvc" (dict "root" $ "name" "functions" "enabled" .Values.deployment.functions.enabled) }}
---
{{ include "supabase.pvc" (dict "root" $ "name" "imgproxy" "enabled" .Values.deployment.imgproxy.enabled) }}
---
{{ include "supabase.pvc" (dict "root" $ "name" "minio" "enabled" .Values.deployment.minio.enabled) }}
---
{{ include "supabase.pvc" (dict "root" $ "name" "snippets" "enabled" .Values.deployment.studio.enabled) }}
---
{{ include "supabase.pvc" (dict "root" $ "name" "storage" "enabled" .Values.deployment.storage.enabled) }}
---
{{ include "supabase.pvc" (dict "root" $ "name" "deno" "enabled" .Values.deployment.functions.enabled) }}
