{{- if .Values.deployment.storage.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.storage.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.storage.enabled }}
  replicas: {{ .Values.deployment.storage.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.storage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.storage.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supabase.storage.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      {{- with .Values.image.storage.pullSecrets}}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "supabase.storage.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.storage.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-db
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              {{- if .Values.deployment.db.enabled }}
              value: {{ include "supabase.db.fullname" . | quote }}
              {{- else }}
              value: {{ .Values.environment.auth.DB_HOST | quote }}
              {{- end }}
            - name: DB_PORT
              value: {{ .Values.environment.analytics.DB_PORT | quote }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              until pg_isready -h $(DB_HOST) -p $(DB_PORT) -U postgres; do
              echo "Waiting for database to start..."
              sleep 2
              done
            - echo "Database is ready"
        {{- if .Values.deployment.minio.enabled }}
        - name: init-bucket
          image: cgr.dev/chainguard/minio-client:latest-dev
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                {{- if .Values.secret.minio.secretRef }}
                  name: {{ .Values.secret.minio.secretRef }}
                  key: {{ .Values.secret.minio.secretRefKey.user | default "user" }}
                {{- else }}
                  name: {{ include "supabase.secret.minio" . }}
                  key: user
                {{- end }}
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- if .Values.secret.s3.secretRef }}
                  name: {{ .Values.secret.s3.secretRef }}
                  key: {{ .Values.secret.s3.secretRefKey.password | default "password" }}
                {{- else }}
                  name: {{ include "supabase.secret.minio" . }}
                  key: password
                {{- end }}
            - name: GLOBAL_S3_BUCKET
              value: {{ .Values.environment.storage.GLOBAL_S3_BUCKET }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              until /usr/bin/mc alias set supa-minio http://{{ include "supabase.minio.fullname" . }}:{{ .Values.service.minio.port }} $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD; do
                echo "Waiting for minio to start..."
                sleep 2
              done
              /usr/bin/mc mb --ignore-existing supa-minio/$GLOBAL_S3_BUCKET
        {{- end }}
      containers:
        - name: {{ include "supabase.storage.name" $ }}
          securityContext:
            {{- toYaml .Values.deployment.storage.securityContext | nindent 12 }}
          image: "{{ .Values.image.storage.repository }}:{{ .Values.image.storage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.storage.pullPolicy }}
          env:
            {{- range $key, $value := .Values.environment.storage }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.deployment.db.enabled }}
            - name: DB_HOST
              value: {{ include "supabase.db.fullname" . }}
            {{- end }}
            {{- if .Values.deployment.rest.enabled }}
            - name: POSTGREST_URL
              value: http://{{ include "supabase.rest.fullname" . }}:{{ .Values.service.rest.port }}
            {{- end }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.db.secretRef }}
                  name: {{ .Values.secret.db.secretRef }}
                  key: {{ .Values.secret.db.secretRefKey.password | default "password" }}
                  {{- else }}
                  name: {{ include "supabase.secret.db" . }}
                  key: password
                  {{- end }}
            - name: DB_PASSWORD_ENC
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.db.secretRef }}
                  name: {{ .Values.secret.db.secretRef }}
                  key: {{ .Values.secret.db.secretRefKey.password | default "password" }}
                  {{- else }}
                  name: {{ include "supabase.secret.db" . }}
                  key: password_encoded
                  {{- end }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.db.secretRef }}
                  name: {{ .Values.secret.db.secretRef }}
                  key: {{ .Values.secret.db.secretRefKey.database | default "database" }}
                  {{- else }}
                  name: {{ include "supabase.secret.db" . }}
                  key: database
                  {{- end }}
            - name: DATABASE_URL
              value: $(DB_DRIVER)://$(DB_USER):$(DB_PASSWORD_ENC)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?search_path=auth&sslmode=$(DB_SSL)
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.jwt.secretRef }}
                  name: {{ .Values.secret.jwt.secretRef }}
                  key: {{ .Values.secret.jwt.secretRefKey.secret | default "secret" }}
                  {{- else }}
                  name: {{ include "supabase.secret.jwt" . }}
                  key: secret
                  {{- end }}
            - name: ANON_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.jwt.secretRef }}
                  name: {{ .Values.secret.jwt.secretRef }}
                  key: {{ .Values.secret.jwt.secretRefKey.anonKey | default "anonKey" }}
                  {{- else }}
                  name: {{ include "supabase.secret.jwt" . }}
                  key: anonKey
                  {{- end }}
            - name: SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.jwt.secretRef }}
                  name: {{ .Values.secret.jwt.secretRef }}
                  key: {{ .Values.secret.jwt.secretRefKey.serviceKey | default "serviceKey" }}
                  {{- else }}
                  name: {{ include "supabase.secret.jwt" . }}
                  key: serviceKey
                  {{- end }}
            - name: S3_PROTOCOL_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.s3.secretRef }}
                  name: {{ .Values.secret.s3.secretRef }}
                  key: {{ .Values.secret.s3.secretRefKey.keyId | default "keyId" }}
                  {{- else }}
                  name: {{ include "supabase.secret.s3" . }}
                  key: keyId
                  {{- end }}
            - name: S3_PROTOCOL_ACCESS_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.s3.secretRef }}
                  name: {{ .Values.secret.s3.secretRef }}
                  key: {{ .Values.secret.s3.secretRefKey.accessKey | default "accessKey" }}
                  {{- else }}
                  name: {{ include "supabase.secret.s3" . }}
                  key: accessKey
                  {{- end }}
            {{- if .Values.deployment.imgproxy.enabled }}
            - name: IMGPROXY_URL
              value: http://{{ include "supabase.imgproxy.fullname" . }}:{{ .Values.service.imgproxy.port | int }}
            {{- end }}
            
            - name: STORAGE_BACKEND
              value: {{ if .Values.deployment.minio.enabled }}s3{{ else }}file{{ end }}
              
            {{- if .Values.deployment.minio.enabled }}
            - name: GLOBAL_S3_ENDPOINT
              value: http://{{ include "supabase.minio.fullname" . }}:{{ default 9000 .Values.service.minio.port }}
            - name: GLOBAL_S3_PROTOCOl
              value: http
            - name: GLOBAL_S3_FORCE_PATH_STYLE
              value: "true"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                {{- if .Values.secret.minio.secretRef }}
                  name: {{ .Values.secret.minio.secretRef }}
                  key: {{ .Values.secret.minio.secretRefKey.user | default "user" }}
                {{- else }}
                  name: {{ include "supabase.secret.minio" . }}
                  key: user
                {{- end }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                {{- if .Values.secret.s3.secretRef }}
                  name: {{ .Values.secret.s3.secretRef }}
                  key: {{ .Values.secret.s3.secretRefKey.password | default "password" }}
                {{- else }}
                  name: {{ include "supabase.secret.minio" . }}
                  key: password
                {{- end }}
            {{- end }}
          {{- with .Values.deployment.storage.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.storage.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          {{- with .Values.deployment.storage.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- with .Values.deployment.storage.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
            - mountPath: /var/lib/storage
              name: storage-data
      {{- with .Values.deployment.storage.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.storage.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.storage.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: storage-data
          {{- if .Values.persistence.storage.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "supabase.pvc.name" (dict "root" $ "name" "storage") }}
          {{- else }}
          emptyDir:
            medium: ""
          {{- end }}
        {{- with .Values.deployment.storage.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
