{{- if .Values.deployment.storage.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.storage.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.storage.type }}
  ports:
    - port: {{ .Values.service.storage.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.storage.selectorLabels" . | nindent 4 }}
{{- end }}
