{{- if .Values.db.enabled -}}
{{- if .Values.serviceAccount.db.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supabase.db.serviceAccountName" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.db.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
