{{- if .Values.deployment.db.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.db.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.db.type }}
  ports:
    - port: {{ .Values.service.db.port }}
      targetPort: 5432
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.db.selectorLabels" . | nindent 4 }}
{{- end }}
