{{- if .Values.studio.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.studio.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  {{- if not .Values.studio.autoscaling.enabled }}
  replicas: {{ .Values.studio.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.studio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.studio.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supabase.studio.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.studio.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "supabase.studio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.studio.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "supabase.studio.name" $ }}
          securityContext:
            {{- toYaml .Values.studio.securityContext | nindent 12 }}
          image: "{{ .Values.studio.image.repository }}:{{ .Values.studio.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.studio.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.studio.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.kong.enabled }}
            - name: SUPABASE_URL
              value: http://{{ include "supabase.kong.fullname" . }}:{{ .Values.kong.service.port }}
            {{- end }}
            {{- if .Values.meta.enabled }}
            - name: STUDIO_PG_META_URL
              value: http://{{ include "supabase.meta.fullname" . }}:{{ .Values.meta.service.port }}
            {{- end }}

            {{- if .Values.db.enabled }}
            - name: POSTGRES_HOST
              value: {{ include "supabase.db.fullname" . }}
            {{- end }}

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.db.secretRef }}
                  name: {{ .Values.secret.db.secretRef }}
                  key: {{ .Values.secret.db.secretRefKey.database | default "database" }}
                  {{- else }}
                  name: {{ include "supabase.secret.db" . }}
                  key: database
                  {{- end }}

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.db.secretRef }}
                  name: {{ .Values.secret.db.secretRef }}
                  key: {{ .Values.secret.db.secretRefKey.password | default "password" }}
                  {{- else }}
                  name: {{ include "supabase.secret.db" . }}
                  key: password
                  {{- end }}

            - name: PG_META_CRYPTO_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.meta.secretRef }}
                  name: {{ .Values.secret.meta.secretRef }}
                  key: {{ .Values.secret.meta.secretRefKey.cryptoKey | default "cryptoKey" }}
                  {{- else }}
                  name: {{ include "supabase.secret.meta" . }}
                  key: cryptoKey
                  {{- end }}


            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.dashboard.secretRef }}
                  name: {{ .Values.secret.dashboard.secretRef }}
                  key: {{ .Values.secret.dashboard.secretRefKey.openAiApiKey | default "openAiApiKey" }}
                  {{- else }}
                  name: {{ include "supabase.secret.dashboard" . }}
                  key: openAiApiKey
                  {{- end }}

            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.jwt.secretRef }}
                  name: {{ .Values.secret.jwt.secretRef }}
                  key: {{ .Values.secret.jwt.secretRefKey.anonKey | default "anonKey" }}
                  {{- else }}
                  name: {{ include "supabase.secret.jwt" . }}
                  key: anonKey
                  {{- end }}

            - name: SUPABASE_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.jwt.secretRef }}
                  name: {{ .Values.secret.jwt.secretRef }}
                  key: {{ .Values.secret.jwt.secretRefKey.serviceKey | default "serviceKey" }}
                  {{- else }}
                  name: {{ include "supabase.secret.jwt" . }}
                  key: serviceKey
                  {{- end }}

            - name: AUTH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.jwt.secretRef }}
                  name: {{ .Values.secret.jwt.secretRef }}
                  key: {{ .Values.secret.jwt.secretRefKey.secret | default "secret" }}
                  {{- else }}
                  name: {{ include "supabase.secret.jwt" . }}
                  key: secret
                  {{- end }}

            {{- if .Values.analytics.enabled }}
            - name: LOGFLARE_URL
              value: http://{{ include "supabase.analytics.fullname" . }}:{{ .Values.analytics.service.port }}
            - name:  LOGFLARE_PUBLIC_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.analytics.secretRef }}
                  name: {{ .Values.secret.analytics.secretRef }}
                  key: {{ .Values.secret.analytics.secretRefKey.publicAccessToken | default "publicAccessToken" }}
                  {{- else }}
                  name: {{ include "supabase.secret.analytics" . }}
                  key: publicAccessToken
                  {{- end }}
            - name: LOGFLARE_PRIVATE_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.analytics.secretRef }}
                  name: {{ .Values.secret.analytics.secretRef }}
                  key: {{ .Values.secret.analytics.secretRefKey.privateAccessToken | default "privateAccessToken" }}
                  {{- else }}
                  name: {{ include "supabase.secret.analytics" . }}
                  key: privateAccessToken
                  {{- end }}
            {{- end }}
            {{- if .Values.persistence.functions.enabled }}
            - name: EDGE_FUNCTIONS_MANAGEMENT_FOLDER
              value: /home/deno/functions
            {{- end }}
            {{- if .Values.persistence.snippets.enabled }}
            - name: SNIPPETS_MANAGEMENT_FOLDER
              value: /app/snippets
            {{- end }}
          {{- with .Values.studio.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.studio.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- with .Values.studio.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.studio.volumeMounts .Values.persistence.functions.enabled }}
          volumeMounts:
            {{- with .Values.studio.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.persistence.functions.enabled }}
            - name: functions-storage
              mountPath: /home/deno/functions
            {{- end }}
            {{- if .Values.persistence.snippets.enabled }}
            - name: snippets-storage
              mountPath: /app/snippets
            {{- end }}
          {{- end }}
      {{- if or .Values.studio.volumes .Values.persistence.functions.enabled }}
      volumes:
        {{- with .Values.studio.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.persistence.functions.enabled }}
        - name: functions-storage
          persistentVolumeClaim:
            claimName: {{ include "supabase.pvc.name" (dict "root" $ "name" "functions") }}
        {{- end }}
        {{- if .Values.persistence.snippets.enabled }}
        - name: snippets-storage
          persistentVolumeClaim:
            claimName: {{ include "supabase.pvc.name" (dict "root" $ "name" "snippets") }}
        {{- end }}
      {{- end }}
      {{- with .Values.studio.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.studio.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.studio.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
