{{- if .Values.deployment.studio.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.studio.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.studio.type }}
  ports:
    - port: {{ .Values.service.studio.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.studio.selectorLabels" . | nindent 4 }}
{{- end }}
