{{- if .Values.studio.enabled -}}
{{- if .Values.serviceAccount.studio.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supabase.studio.serviceAccountName" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.studio.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
