{{- if .Values.deployment.auth.enabled -}}
{{- if .Values.serviceAccount.auth.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supabase.auth.serviceAccountName" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.auth.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
