{{- if .Values.auth.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.auth.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.auth.type }}
  ports:
    - port: {{ .Values.service.auth.port }}
      targetPort: 9999
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.auth.selectorLabels" . | nindent 4 }}
{{- end }}
