{{- if .Values.secret.realtime }}
{{- if not .Values.secret.realtime.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.realtime" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secret.realtime }}
{{- if $value }}
{{- if eq (typeOf $value) "string" }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
