{{- if .Values.deployment.imgproxy.enabled -}}
{{- if .Values.serviceAccount.imgproxy.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supabase.imgproxy.serviceAccountName" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.imgproxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
