{{- if .Values.realtime.enabled -}}
{{- if .Values.serviceAccount.realtime.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supabase.realtime.serviceAccountName" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.realtime.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
