{{- if and .Values.functions.enabled .Values.functions.persistence.enabled (not .Values.functions.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "supabase.functions.persistenceClaimName" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.functions.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.functions.persistence.storageClassName }}
  storageClassName: {{ .Values.functions.persistence.storageClassName }}
  {{- end }}
  accessModes:
    {{- range .Values.functions.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.functions.persistence.size | quote }}
{{- end }}
