{{- if .Values.functions.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.functions.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.functions.type }}
  ports:
    - port: {{ .Values.service.functions.port }}
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.functions.selectorLabels" . | nindent 4 }}
{{- end }}
