{{- if .Values.deployment.functions.enabled -}}
{{- if .Values.serviceAccount.functions.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supabase.functions.serviceAccountName" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.functions.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
