{{- if .Values.analytics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.analytics.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.analytics.type }}
  ports:
    - port: {{ .Values.service.analytics.port }}
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.analytics.selectorLabels" . | nindent 4 }}
{{- end }}
