{{- if .Values.meta.enabled -}}
{{- if .Values.serviceAccount.meta.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supabase.meta.serviceAccountName" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.meta.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
